### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by chicoband** [collinalexbell/HackMatrix#69]
Hey,

Great project! Could you please clarify the licensing status of this project as it appears to lack a license?

Thanks!

**Comment by collinalexbell** [comment]
Sure. MIT. Just added it to the repo.

**Comment by Ryman** [comment]
@collinalexbell Hey, the license situation might still be a little unclear since [octree](https://github.com/collinalexbell/HackMatrix/tree/master/include/octree) is included which is GPLv3 which is [viral even with linking AFAIU](https://opensource.stackexchange.com/questions/15285/can-i-use-copyleft-licensed-library-in-mit-licensed-project). It might be worthwhile to replace with an [MIT alternative](https://github.com/annell/octree-cpp)?

**Comment by collinalexbell** [comment]
I can remove the header at some point

**Comment by collinalexbell** [comment]
I've removed the library.
